### ISSUE TITLE
FFmpeg failed to build

### ISSUE THREAD

**Issue by sclsj** [homebrew-ffmpeg/homebrew-ffmpeg#15] opened 2020-01-12 06:31 UTC
Command:
brew install homebrew-ffmpeg/ffmpeg/ffmpeg  --with-decklink --with-fdk-aac --with-game-music-emu --with-libbluray --with-libbs2b --with-libcaca --with-libgsm --with-libmodplug --with-librsvg --with-libsoxr --with-libssh --with-libvidstab --with-libvmaf --with-libxml2 --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-rtmpdump --with-rubberband --with-speex --with-srt --with-tesseract --with-two-lame --with-wavpack --with-webp --with-xvid --with-zeromq --with-zimg
Output:
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/4.2.1-with-options_2 --enable-
==> make install
Last 15 lines from /Users/Jin/Library/Logs/Homebrew/ffmpeg/02.make:
        u_char  p_priority;     /* Process priority. */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/proc.h:134:2: error: unknown type name 'u_char'; did you mean 'char'?
        u_char  p_usrpri;       /* User-priority based on p_cpu and p_nice. */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/proc.h:139:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short p_xstat;        /* Exit status for wait; also stop signal. */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/proc.h:140:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short p_acflag;       /* Accounting flags. */
        ^
9 errors generated.
make: *** [libavutil/cpu.o] Error 1
make: *** Waiting for unfinished jobs....
STRIP	libswscale/x86/scale.o

[log/homebrew/ffmpeg.zip](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/files/4050281/log.homebrew.ffmpeg.zip)

**Comment by retokromer** [comment] 2020-01-12 11:57
Just wondering: why do you use FFmpeg 4.2.1

>==> ./configure --prefix=/usr/local/Cellar/ffmpeg/4.2.1-with-options_2

and not the formula for FFmpeg 4.2.2 which we did release one week earlier? And did other change other things? (I am asking because the formula does not generate a `_2`.)

**Comment by sclsj** [comment] 2020-01-13 08:32
I just run the command with all arguments (except for chromaprint because ffmpeg is its dependency). I can try again.

**Comment by sclsj** [comment] 2020-01-13 08:39
I updated homebrew and run the command again. Here's the new output (note that the version is 4.2.2)
==> Installing homebrew-ffmpeg/ffmpeg/ffmpeg --with-decklink --with-fd
==> Downloading https://ffmpeg.org/releases/ffmpeg-4.2.2.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/4.2.2-with-options --enable-shared --cc=clang --host-cflags=-I/Library/Java/JavaVirtualMachines/jdk-12.jdk/Contents/Home/include -I/Library/Java/JavaVir
==> make install
Last 15 lines from /Users/Jin/Library/Logs/Homebrew/ffmpeg/02.make:
        u_char  p_priority;     /* Process priority. */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/proc.h:134:2: error: unknown type name 'u_char'; did you mean 'char'?
        u_char  p_usrpri;       /* User-priority based on p_cpu and p_nice. */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/proc.h:139:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short p_xstat;        /* Exit status for wait; also stop signal. */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/proc.h:140:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short p_acflag;       /* Accounting flags. */
        ^
9 errors generated.
make: *** [libavutil/cpu.o] Error 1
make: *** Waiting for unfinished jobs....
STRIP	libswscale/x86/scale.o

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues

These open issues may also help:
FFmpeg failed to build https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/15
building with --with-chromaprint problem, recursive dependency on ffmpeg https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/13

**Comment by retokromer** [comment] 2020-01-13 08:52
Thank you for reporting back! I can probably delve into it this evening.

**Comment by retokromer** [comment] 2020-06-25 12:01
@sclsj Do you still encounter this issue? I could not reproduce.

Regarding the `--with-decklink` option: the DeckLink SDK has to be installed **before** running the FFmpeg formula. One possibility is to use:
```
brew install amiaopensource/amiaos/decklinksdk
```
See the [ReadMe](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg#included-libraries).

**Comment by sclsj** [comment] 2020-06-26 00:59
@retokromer I build it on my own without homebrew. I used 'make -n' to find the actual compiler flag and deleted all header directories except for the default ones, and it worked. I think something is probably defined in more than one header file and the incorrect one is used.

**Comment by sclsj** [comment] 2020-06-26 00:59
I have too many programs in /usr/local/ so I don't know which program caused that.

**Comment by retokromer** [comment] 2020-06-26 04:40
Thank you, @sclsj, for reporting back!

>I think something is probably defined in more than one header file and the incorrect one is used.

This seems not related to our formula and I will close the issue, but feel free to reopen it when you have other information.

**Closed by retokromer** 2020-06-26 04:40 UTC
