### ISSUE TITLE
OpenSSL not enabled in youtube-dl?

### ISSUE THREAD

**Issue by sxflynn** [homebrew-ffmpeg/homebrew-ffmpeg#71] opened 2021-03-08 15:48 UTC
- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew config` and `brew doctor` and included their output with your issue?

## Expected behavior

I ran the command ```youtube-dl https://www.cbsnews.com/video/60minutes-2021-03-07/#x``` and it should just download it since FFMPEG is included in Youtube-DL and I compiled ffmpeg with openssl.

## Actual behavior

I ran the command above and I got an error and it failed. Keep in mind that I used this tap to install FFMPEG and I selected ```brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-openssl```

## Command

The exact command you were trying to run:

```
youtube-dl https://www.cbsnews.com/video/60minutes-2021-03-07/#x
```

The output that you got:

```
https protocol not found, recompile FFmpeg with openssl, gnutls,
or securetransport enabled.
https://prod.vodvideo.cbsnews.com/cbsnews/vr/hls/2021/02/11/1858978371560/662502_hls/0307_60_full_662502_3000/stream.m3u8: Protocol not found
```

## Output of `brew config` and `brew doctor` commands

```
HOMEBREW_VERSION: 3.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: ee52b19179d056f3dd2fdf9c52214d3d51dbb9d9
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e5cf1a1a7da039a0e654b70725a1c1fe39626cd9
Core tap last commit: 24 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

```
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5m-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4m-config
  /Library/Frameworks/Python.framework/Versions/3.4/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ffmpeg
  python@3.9

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> /Users/sflynn/.bash_profile
```

**Comment by slhck** [comment] 2021-03-08 15:55
When you type `ffmpeg` on your command line, does it show HTTPS support in the configuration line? Please show the output of a simple `ffmpeg` call.

PS:

```
Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ffmpeg
```

This may be an issue in other contexts; make sure you successfully ran `brew uninstall ffmpeg` before installing this tap.

**Comment by retokromer** [comment] 2021-03-08 15:56
On macOS 10.14.6 you should have Clang 11.0 build 1100.

**Comment by sxflynn** [comment] 2021-03-08 16:13
Here is my ffmpeg output:

```ffmpeg version 2.8.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with llvm-gcc 4.2.1 (LLVM build 2336.11.00)
  configuration: --prefix=/Volumes/Ramdisk/sw --enable-gpl --enable-pthreads --enable-version3 --enable-libspeex --enable-libvpx --disable-decoder=libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libgsm --enable-libvidstab --enable-libx265 --disable-doc --arch=x86_64 --enable-runtime-cpudetect
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

**Comment by retokromer** [comment] 2021-03-08 16:38
Sadly the first line in missing. Yet what is the reason for compiling with LLVM rather than Clang on macOS? I also notice that the libraries are not recent ones. You should uninstall the old version of FFmpeg and then install the current one.

**Comment by retokromer** [comment] 2021-03-08 16:49
On my end, I got (without any option):
```
ffmpeg version 4.3.2 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.2-with-options --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --disable-libjack --disable-indev=jack --enable-opencl --enable-videotoolbox --disable-htmlpages
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

**Comment by retokromer** [comment] 2021-03-08 16:52
… and the output of `brew config` reads:
```
HOMEBREW_VERSION: 3.0.4-64-g31a4989
ORIGIN: https://github.com/Homebrew/brew
HEAD: 31a4989358f0a5bf5be3ea4695053677ab528f28
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e5cf1a1a7da039a0e654b70725a1c1fe39626cd9
Core tap last commit: 87 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 11.0 build 1100
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1
```

**Comment by retokromer** [comment] 2021-03-08 17:01
I cannot reproduce the `youtube-dl` error. On my end it works just fine.

**Comment by sxflynn** [comment] 2021-03-08 17:14
Sorry, I edited my comment so it shows the first line. I'm running ffmpeg 2.8.2

**Comment by retokromer** [comment] 2021-03-08 17:19
What is the output of `which -a ffmpeg`?

**Comment by sxflynn** [comment] 2021-03-08 17:24
```/usr/local/bin/ffmpeg```

**Comment by slhck** [comment] 2021-03-08 17:26
You have some old, very outdated ffmpeg version in `/usr/local/bin/`. It's certainly not the Homebrew version.

Please try installing ffmpeg from this tap again and show the entire output. Does the `link` step in the end succeed?

**Comment by retokromer** [comment] 2021-03-08 17:27
And what is `/usr/local/bin/ffmpeg -version`?

**Comment by sxflynn** [comment] 2021-03-08 17:33
> And what is `/usr/local/bin/ffmpeg -version`?
```
ffmpeg version 2.8.2 Copyright (c) 2000-2015 the FFmpeg developers
built with llvm-gcc 4.2.1 (LLVM build 2336.11.00)
configuration: --prefix=/Volumes/Ramdisk/sw --enable-gpl --enable-pthreads --enable-version3 --enable-libspeex --enable-libvpx --disable-decoder=libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libgsm --enable-libvidstab --enable-libx265 --disable-doc --arch=x86_64 --enable-runtime-cpudetect
libavutil      54. 31.100 / 54. 31.100
libavcodec     56. 60.100 / 56. 60.100
libavformat    56. 40.101 / 56. 40.101
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 40.101 /  5. 40.101
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.101 /  1.  2.101
libpostproc    53.  3.100 / 53.  3.100
```

**Comment by sxflynn** [comment] 2021-03-08 17:38
I just renamed ffmpeg to ffmpeg_28 and I am now installing again

```
brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-openssl --with-rav1e
```

**Comment by sxflynn** [comment] 2021-03-08 17:58
Now this is my ```ffmpeg``` output:

```
ffmpeg version 4.3.2 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.2-with-options --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --disable-libjack --disable-indev=jack --enable-opencl --enable-videotoolbox --disable-htmlpages --enable-openssl --enable-nonfree
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Hyper fast Audio and Video encoder
```

**Comment by sxflynn** [comment] 2021-03-08 18:02
Youtube-DL is now proceeding with the download and repatching the segments. It worked!

Before we close this issue, do you think it's an issue that I should post with the top level homebrew community, that homebrew should somehow check to see that it's not actually installing anything over my old version? That seems like a flaw that should be addressed. Or do you think my problem was not very common?

**Comment by retokromer** [comment] 2021-03-08 18:18
I guess this is already included in Homebrew’s documentation. In any case, this issue is not related to our formula, therefore I’m closing it.

**Closed by retokromer** 2021-03-08 18:18 UTC

**Comment by slhck** [comment] 2021-03-08 18:25
I believe that Homebrew should have warned you in the last step, failing to link the ffmpeg binary to its final location. So the behavior you're suggesting should already be implemented.
If you hadn't renamed the existing binary you would have probably seen it.
