### ISSUE TITLE
unable to use openCL lookahead

### ISSUE THREAD

**Issue by exekutive** [homebrew-ffmpeg/homebrew-ffmpeg#61] opened 2020-10-30 07:50 UTC
input
`ffmpeg -hwaccel auto -i "in.wmv" -c:v libx264 -preset slower -movflags +faststart -c:a libfdk_aac -ac 1 -vbr 1 -ar 8000 -x264opts opencl "out.mp4" `

output
```
[libx264 @ 0x7f910d01c000] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7f910d01c000] OpenCL acceleration enabled with Intel Iris Pro 
[libx264 @ 0x7f910d01c000] Compiling OpenCL kernels...
[libx264 @ 0x7f910d01c000] OpenCL: OpenCL Build Warning : Compiler build log:
<program source>:91:5: warning: no previous prototype for function 'parallel_sum'
int parallel_sum( int value, int x, volatile local int *array )
    ^
<program source>:106:5: warning: no previous prototype for function 'mv_cost'
int mv_cost( uint2 mvd )
    ^
<program source>:116:5: warning: no previous prototype for function 'bidir_satd_8x8_ii_coop4'
int bidir_satd_8x8_ii_coop4( read_only image2d_t fenc_lowres,
    ^
<program source>:372:31: warning: comparison of integers of different signs: 'int' and 'unsigned long'
const global pixel *src2 = (y == get_global_size( 1 )-1) ? src1 : src1 + stride;
                            ~ ^  ~~~~~~~~~~~~~~~~~~~~~~
<program source>:389:25: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long')
x = select( x, x+1, x+1 < get_global_size( 0 ) );
                    ~~~ ^ ~~~~~~~~~~~~~~~~~~~~
<program source>:393:25: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long')
x = select( x, x+1, x+1 < get_global_size( 0 ) );
                    ~~~ ^ ~~~~~~~~~~~~~~~~~~~~
<program source>:397:25: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long')
x = select( x, x+1, x+1 < get_global_size( 0 ) );
                    ~~~ ^ ~~~~~~~~~~~~~~~~~~~~
<program source>:503:15: warning: no previous prototype for function 'satd_8x4_lp'
SATD_C_8x4_Q( satd_8x4_lp, const local, private )
              ^
<program source>:68:5: note: expanded from macro 'SATD_C_8x4_Q'
int name( q1 pixel *pix1, int i_pix1, q2 pixel *pix2, int i_pix2 )\
    ^
<program source>:895:5: warning: no previous prototype for function 'x264_predict_8x8_ddl'
int x264_predict_8x8_ddl( const local pixel *src, int src_stride, const local pixel *top )
    ^
<program source>:919:5: warning: no previous prototype for function 'x264_predict_8x8_ddr'
int x264_predict_8x8_ddr( const local pixel *src, int src_stride, const local pixel *top, const local pixel *left, pixel left_top )
    ^
<program source>:950:5: warning: no previous prototype for function 'x264_predict_8x8_vr'
int x264_predict_8x8_vr( const local pixel *src, int src_stride, const local pixel *top, const local pixel *left, pixel left_top )
    ^
<program source>:1003:5: warning: no previous prototype for function 'x264_predict_8x8_hd'
int x264_predict_8x8_hd( const local pixel *src, int src_stride, const local pixel *top, const local pixel *left, pixel left_top )
    ^
<program source>:1038:5: warning: no previous prototype for function 'x264_predict_8x8_vl'
int x264_predict_8x8_vl( const local pixel *src, int src_stride, const local pixel *top )
    ^
<program source>:1084:5: warning: no previous prototype for function 'x264_predict_8x8_hu'
int x264_predict_8x8_hu( const local pixel *src, int src_stride, const local pixel *left )
    ^
<program source>:1116:5: warning: no previous prototype for function 'x264_predict_8x8c_h'
int x264_predict_8x8c_h( const local pixel *src, int src_stride )
    ^
<program source>:1131:5: warning: no previous prototype for function 'x264_predict_8x8c_v'
int x264_predict_8x8c_v( const local pixel *src, int src_stride )
    ^
<program source>:1142:5: warning: no previous prototype for function 'x264_predict_8x8c_p'
int x264_predict_8x8c_p( const local pixel *src, int src_stride )
    ^
<program source>:1180:5: warning: no previous prototype for function 'x264_predict_8x8c_dc'
int x264_predict_8x8c_dc( const local pixel *src, int src_stride )
    ^
<program source>:1387:5: warning: no previous prototype for function 'sad_8x8_ii_coop4'
int sad_8x8_ii_coop4( read_only image2d_t fenc, int2 fencpos, read_only image2d_t fref, int2 frefpos, int idx, local int16_t *costs )
    ^
<program source>:1429:5: warning: no previous prototype for function 'sad_8x8_ii'
int sad_8x8_ii( read_only image2d_t fenc, int2 fencpos, read_only image2d_t fref, int2 frefpos )
    ^
<program source>:1611:5: warning: no previous prototype for function 'sad_8x8_ii_hpel'
int sad_8x8_ii_hpel( read_only image2d_t fenc, int2 fencpos, read_only image2d_t fref_planes, int2 qpos )
    ^
<program source>:1636:5: warning: no previous prototype for function 'sad_8x8_ii_qpel'
int sad_8x8_ii_qpel( read_only image2d_t fenc, int2 fencpos, read_only image2d_t fref_planes, int2 qpos )
    ^
<program source>:1662:5: warning: no previous prototype for function 'satd_8x8_ii_qpel_coop4'
int satd_8x8_ii_qpel_coop4( read_only image2d_t fenc,
    ^


[libx264 @ 0x7f910d01c000] OpenCL: fatal error, aborting encode
[libx264 @ 0x7f910d01c000] profile High, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x7f910d01c000] 264 - core 161 r3018M db0d417 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=8 deblock=1:0:0 analyse=0x3:0x133 me=umh subme=9 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=2 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=60 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Video encoding failed
Conversion failed!
```

**Comment by retokromer** [comment] 2020-11-07 16:25
@exekutive The current version of `x264` is `r3027`. Could you possibly upgrade and test again? Please include the full command line you have tested and the full terminal output you got with.

**Comment by exekutive** [comment] 2020-11-08 09:56
same problem with r3027

```
ffmpeg -hwaccel auto -i "sample.WMV" -c:v libx264 -preset slower -movflags +faststart -c:a libfdk_aac -ac 1 -vbr 1 -ar 8000 -x264opts opencl "out.mp4"
ffmpeg version git-2020-11-07-8fbcc54 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.27)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/HEAD-8fbcc54_6 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --disable-libjack --disable-indev=jack --enable-opencl --enable-videotoolbox --disable-htmlpages --enable-chromaprint --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfdk-aac --enable-libgsm --enable-libmodplug --enable-libopenh264 --enable-libopenjpeg --enable-librsvg --enable-librtmp --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtesseract --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libwebp --enable-libxvid --enable-libzimg --enable-libzmq --enable-openssl --enable-nonfree --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb
  libavutil      56. 60.100 / 56. 60.100
  libavcodec     58.112.101 / 58.112.101
  libavformat    58. 64.100 / 58. 64.100
  libavdevice    58. 11.102 / 58. 11.102
  libavfilter     7. 89.100 /  7. 89.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, asf, from 'sample.WMV':
  Metadata:
    WMFSDKNeeded    : 0.0.0.0000
    DeviceConformanceTemplate: @
    WM/WMADRCPeakReference: 32767
    WM/WMADRCAverageReference: 13531
    WMFSDKVersion   : 9.00.00.2980
    IsVBR           : 0
    title           : CNN C1
    artist          : migdom
    copyright       : 5/11/2004
  Duration: 00:00:12.03, start: 0.000000, bitrate: 123 kb/s
    Chapter #0:0: start 0.000000, end 12.032000
    Metadata:
      title           : Clip 6
    Stream #0:0(eng): Audio: wmav2 (a[1][0][0] / 0x0161), 16000 Hz, mono, fltp, 16 kb/s
    Stream #0:1(eng): Video: wmv1 (WMV1 / 0x31564D57), yuv420p, 320x240, 80 kb/s, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 1k tbn, 1k tbc
Stream mapping:
  Stream #0:1 -> #0:0 (wmv1 (native) -> h264 (libx264))
  Stream #0:0 -> #0:1 (wmav2 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[libx264 @ 0x7fd78482f200] using SAR=1/1
[libx264 @ 0x7fd78482f200] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7fd78482f200] OpenCL acceleration enabled with Intel Inc. Intel(R) UHD Graphics 630 
[libx264 @ 0x7fd78482f200] Compiling OpenCL kernels...
[libx264 @ 0x7fd78482f200] OpenCL: OpenCL Build Warning : Compiler build log:
<program source>:91:5: warning: no previous prototype for function 'parallel_sum'
int parallel_sum( int value, int x, volatile local int *array )
    ^
<program source>:106:5: warning: no previous prototype for function 'mv_cost'
int mv_cost( uint2 mvd )
    ^
<program source>:116:5: warning: no previous prototype for function 'bidir_satd_8x8_ii_coop4'
int bidir_satd_8x8_ii_coop4( read_only image2d_t fenc_lowres,
    ^
<program source>:372:31: warning: comparison of integers of different signs: 'int' and 'unsigned long'
const global pixel *src2 = (y == get_global_size( 1 )-1) ? src1 : src1 + stride;
                            ~ ^  ~~~~~~~~~~~~~~~~~~~~~~
<program source>:389:25: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long')
x = select( x, x+1, x+1 < get_global_size( 0 ) );
                    ~~~ ^ ~~~~~~~~~~~~~~~~~~~~
<program source>:393:25: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long')
x = select( x, x+1, x+1 < get_global_size( 0 ) );
                    ~~~ ^ ~~~~~~~~~~~~~~~~~~~~
<program source>:397:25: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long')
x = select( x, x+1, x+1 < get_global_size( 0 ) );
                    ~~~ ^ ~~~~~~~~~~~~~~~~~~~~
<program source>:503:15: warning: no previous prototype for function 'satd_8x4_lp'
SATD_C_8x4_Q( satd_8x4_lp, const local, private )
              ^
<program source>:68:5: note: expanded from macro 'SATD_C_8x4_Q'
int name( q1 pixel *pix1, int i_pix1, q2 pixel *pix2, int i_pix2 )\
    ^
<program source>:895:5: warning: no previous prototype for function 'x264_predict_8x8_ddl'
int x264_predict_8x8_ddl( const local pixel *src, int src_stride, const local pixel *top )
    ^
<program source>:919:5: warning: no previous prototype for function 'x264_predict_8x8_ddr'
int x264_predict_8x8_ddr( const local pixel *src, int src_stride, const local pixel *top, const local pixel *left, pixel left_top )
    ^
<program source>:950:5: warning: no previous prototype for function 'x264_predict_8x8_vr'
int x264_predict_8x8_vr( const local pixel *src, int src_stride, const local pixel *top, const local pixel *left, pixel left_top )
    ^
<program source>:1003:5: warning: no previous prototype for function 'x264_predict_8x8_hd'
int x264_predict_8x8_hd( const local pixel *src, int src_stride, const local pixel *top, const local pixel *left, pixel left_top )
    ^
<program source>:1038:5: warning: no previous prototype for function 'x264_predict_8x8_vl'
int x264_predict_8x8_vl( const local pixel *src, int src_stride, const local pixel *top )
    ^
<program source>:1084:5: warning: no previous prototype for function 'x264_predict_8x8_hu'
int x264_predict_8x8_hu( const local pixel *src, int src_stride, const local pixel *left )
    ^
<program source>:1116:5: warning: no previous prototype for function 'x264_predict_8x8c_h'
int x264_predict_8x8c_h( const local pixel *src, int src_stride )
    ^
<program source>:1131:5: warning: no previous prototype for function 'x264_predict_8x8c_v'
int x264_predict_8x8c_v( const local pixel *src, int src_stride )
    ^
<program source>:1142:5: warning: no previous prototype for function 'x264_predict_8x8c_p'
int x264_predict_8x8c_p( const local pixel *src, int src_stride )
    ^
<program source>:1180:5: warning: no previous prototype for function 'x264_predict_8x8c_dc'
int x264_predict_8x8c_dc( const local pixel *src, int src_stride )
    ^
<program source>:1387:5: warning: no previous prototype for function 'sad_8x8_ii_coop4'
int sad_8x8_ii_coop4( read_only image2d_t fenc, int2 fencpos, read_only image2d_t fref, int2 frefpos, int idx, local int16_t *costs )
    ^
<program source>:1429:5: warning: no previous prototype for function 'sad_8x8_ii'
int sad_8x8_ii( read_only image2d_t fenc, int2 fencpos, read_only image2d_t fref, int2 frefpos )
    ^
<program source>:1611:5: warning: no previous prototype for function 'sad_8x8_ii_hpel'
int sad_8x8_ii_hpel( read_only image2d_t fenc, int2 fencpos, read_only image2d_t fref_planes, int2 qpos )
    ^
<program source>:1636:5: warning: no previous prototype for function 'sad_8x8_ii_qpel'
int sad_8x8_ii_qpel( read_only image2d_t fenc, int2 fencpos, read_only image2d_t fref_planes, int2 qpos )
    ^
<program source>:1662:5: warning: no previous prototype for function 'satd_8x8_ii_qpel_coop4'
int satd_8x8_ii_qpel_coop4( read_only image2d_t fenc,
    ^


[libx264 @ 0x7fd78482f200] OpenCL: fatal error, aborting encode
[libx264 @ 0x7fd78482f200] profile Progressive High, level 2.1, 4:2:0, 8-bit
[libx264 @ 0x7fd78482f200] 264 - core 157 r2971M 98ee9d2 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=8 deblock=1:0:0 analyse=0x3:0x133 me=umh subme=9 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=7 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=2 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=60 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Video encoding failed
Conversion failed!
```

**Comment by retokromer** [comment] 2020-11-08 10:27
It seems you are now on an older `libx264` than before. I cannot reproduce on my end with the current head.

**Comment by exekutive** [comment] 2020-11-08 21:20
<img width="777" alt="Screen Shot 2020-11-08 at 13 19 24" src="https://user-images.githubusercontent.com/4755215/98484539-1d5f7080-21c5-11eb-8fc1-cd37061f5c2c.png">

**Comment by retokromer** [comment] 2020-11-09 08:06
I am afraid, I cannot understand your error. Before it  was

>[libx264 @ 0x7f910d01c000] 264 - **core 161 r3018M db0d417** - H.264/MPEG-4 AVC codec - **Copyleft 2003-2020** - http://www.videolan.org/x264.html - options: cabac=1 ref=8 deblock=1:0:0 analyse=0x3:0x133 me=umh subme=9 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=2 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=60 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00

and now it is

>[libx264 @ 0x7fd78482f200] 264 - **core 157 r2971M 98ee9d2** - H.264/MPEG-4 AVC codec - **Copyleft 2003-2019** - http://www.videolan.org/x264.html - options: cabac=1 ref=8 deblock=1:0:0 analyse=0x3:0x133 me=umh subme=9 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=7 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=2 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=60 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00

If I will find the time, I am giving another try this eveninng.

**Comment by exekutive** [comment] 2020-11-13 19:47
There was a problem with x264
https://github.com/Homebrew/homebrew-core/issues/64650

**Comment by retokromer** [comment] 2020-11-13 19:55
This should be resolved now.

**Comment by exekutive** [comment] 2020-11-13 20:05
sadly no

```
>ffmpeg -hwaccel auto -i "/Users/joe/Documents/MacOS/ffmpeg/sample.WMV" -c:v libx264 -preset slower -movflags +faststart -c:a libfdk_aac -ac 1 -vbr 1 -ar 8000 -x264opts opencl "/Users/joe/Documents/MacOS/ffmpeg/out.mp4"   
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.27)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1-with-options_6 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --disable-libjack --disable-indev=jack --enable-opencl --enable-videotoolbox --disable-htmlpages --enable-chromaprint --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfdk-aac --enable-libgsm --enable-libmodplug --enable-libopenh264 --enable-libopenjpeg --enable-librsvg --enable-librtmp --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtesseract --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libwavpack --enable-libwebp --enable-libxvid --enable-libzimg --enable-libzmq --enable-openssl --enable-nonfree --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, asf, from '/Users/joe/Documents/MacOS/ffmpeg/sample.WMV':
  Metadata:
    WMFSDKNeeded    : 0.0.0.0000
    DeviceConformanceTemplate: @
    WM/WMADRCPeakReference: 32767
    WM/WMADRCAverageReference: 13531
    WMFSDKVersion   : 9.00.00.2980
    IsVBR           : 0
    title           : CNN C1
    artist          : migdom
    copyright       : 5/11/2004
  Duration: 00:00:12.03, start: 0.000000, bitrate: 123 kb/s
    Chapter #0:0: start 0.000000, end 12.032000
    Metadata:
      title           : Clip 6
    Stream #0:0(eng): Audio: wmav2 (a[1][0][0] / 0x0161), 16000 Hz, mono, fltp, 16 kb/s
    Stream #0:1(eng): Video: wmv1 (WMV1 / 0x31564D57), yuv420p, 320x240, 80 kb/s, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 1k tbn, 1k tbc
Stream mapping:
  Stream #0:1 -> #0:0 (wmv1 (native) -> h264 (libx264))
  Stream #0:0 -> #0:1 (wmav2 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[libx264 @ 0x7fbdff826000] using SAR=1/1
[libx264 @ 0x7fbdff826000] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7fbdff826000] OpenCL acceleration enabled with Intel Inc. Intel(R) UHD Graphics 630 
[libx264 @ 0x7fbdff826000] Compiling OpenCL kernels...
[libx264 @ 0x7fbdff826000] OpenCL: OpenCL Build Warning : Compiler build log:
<program source>:91:5: warning: no previous prototype for function 'parallel_sum'
int parallel_sum( int value, int x, volatile local int *array )
    ^
<program source>:106:5: warning: no previous prototype for function 'mv_cost'
int mv_cost( uint2 mvd )
    ^
<program source>:116:5: warning: no previous prototype for function 'bidir_satd_8x8_ii_coop4'
int bidir_satd_8x8_ii_coop4( read_only image2d_t fenc_lowres,
    ^
<program source>:372:31: warning: comparison of integers of different signs: 'int' and 'unsigned long'
const global pixel *src2 = (y == get_global_size( 1 )-1) ? src1 : src1 + stride;
                            ~ ^  ~~~~~~~~~~~~~~~~~~~~~~
<program source>:389:25: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long')
x = select( x, x+1, x+1 < get_global_size( 0 ) );
                    ~~~ ^ ~~~~~~~~~~~~~~~~~~~~
<program source>:393:25: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long')
x = select( x, x+1, x+1 < get_global_size( 0 ) );
                    ~~~ ^ ~~~~~~~~~~~~~~~~~~~~
<program source>:397:25: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long')
x = select( x, x+1, x+1 < get_global_size( 0 ) );
                    ~~~ ^ ~~~~~~~~~~~~~~~~~~~~
<program source>:503:15: warning: no previous prototype for function 'satd_8x4_lp'
SATD_C_8x4_Q( satd_8x4_lp, const local, private )
              ^
<program source>:68:5: note: expanded from macro 'SATD_C_8x4_Q'
int name( q1 pixel *pix1, int i_pix1, q2 pixel *pix2, int i_pix2 )\
    ^
<program source>:895:5: warning: no previous prototype for function 'x264_predict_8x8_ddl'
int x264_predict_8x8_ddl( const local pixel *src, int src_stride, const local pixel *top )
    ^
<program source>:919:5: warning: no previous prototype for function 'x264_predict_8x8_ddr'
int x264_predict_8x8_ddr( const local pixel *src, int src_stride, const local pixel *top, const local pixel *left, pixel left_top )
    ^
<program source>:950:5: warning: no previous prototype for function 'x264_predict_8x8_vr'
int x264_predict_8x8_vr( const local pixel *src, int src_stride, const local pixel *top, const local pixel *left, pixel left_top )
    ^
<program source>:1003:5: warning: no previous prototype for function 'x264_predict_8x8_hd'
int x264_predict_8x8_hd( const local pixel *src, int src_stride, const local pixel *top, const local pixel *left, pixel left_top )
    ^
<program source>:1038:5: warning: no previous prototype for function 'x264_predict_8x8_vl'
int x264_predict_8x8_vl( const local pixel *src, int src_stride, const local pixel *top )
    ^
<program source>:1084:5: warning: no previous prototype for function 'x264_predict_8x8_hu'
int x264_predict_8x8_hu( const local pixel *src, int src_stride, const local pixel *left )
    ^
<program source>:1116:5: warning: no previous prototype for function 'x264_predict_8x8c_h'
int x264_predict_8x8c_h( const local pixel *src, int src_stride )
    ^
<program source>:1131:5: warning: no previous prototype for function 'x264_predict_8x8c_v'
int x264_predict_8x8c_v( const local pixel *src, int src_stride )
    ^
<program source>:1142:5: warning: no previous prototype for function 'x264_predict_8x8c_p'
int x264_predict_8x8c_p( const local pixel *src, int src_stride )
    ^
<program source>:1180:5: warning: no previous prototype for function 'x264_predict_8x8c_dc'
int x264_predict_8x8c_dc( const local pixel *src, int src_stride )
    ^
<program source>:1387:5: warning: no previous prototype for function 'sad_8x8_ii_coop4'
int sad_8x8_ii_coop4( read_only image2d_t fenc, int2 fencpos, read_only image2d_t fref, int2 frefpos, int idx, local int16_t *costs )
    ^
<program source>:1429:5: warning: no previous prototype for function 'sad_8x8_ii'
int sad_8x8_ii( read_only image2d_t fenc, int2 fencpos, read_only image2d_t fref, int2 frefpos )
    ^
<program source>:1611:5: warning: no previous prototype for function 'sad_8x8_ii_hpel'
int sad_8x8_ii_hpel( read_only image2d_t fenc, int2 fencpos, read_only image2d_t fref_planes, int2 qpos )
    ^
<program source>:1636:5: warning: no previous prototype for function 'sad_8x8_ii_qpel'
int sad_8x8_ii_qpel( read_only image2d_t fenc, int2 fencpos, read_only image2d_t fref_planes, int2 qpos )
    ^
<program source>:1662:5: warning: no previous prototype for function 'satd_8x8_ii_qpel_coop4'
int satd_8x8_ii_qpel_coop4( read_only image2d_t fenc,
    ^


[libx264 @ 0x7fbdff826000] OpenCL: fatal error, aborting encode
[libx264 @ 0x7fbdff826000] OpenCL: unable to open clbin file for write
[libx264 @ 0x7fbdff826000] profile High, level 2.1, 4:2:0, 8-bit
[libx264 @ 0x7fbdff826000] 264 - core 161 r3027 4121277 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=8 deblock=1:0:0 analyse=0x3:0x133 me=umh subme=9 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=7 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=2 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=60 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Video encoding failed
Conversion failed!
```

**Comment by exekutive** [comment] 2020-11-13 20:08
Also, I notice that ffmpeg is trying to use the integrated Intel GPU for openCL, even though this MBP has a more powerful Radeon GPU installed.

**Comment by retokromer** [comment] 2020-11-14 06:11
I meant the problem with the installation of x264 via Homebrew.

I am afraid, I cannot reproduce on my end neither with the current head, nor with release 4.3.1.

**Comment by exekutive** [comment] 2020-11-14 08:12
I have produced the issue on two separate macbooks.

**Comment by retokromer** [comment] 2020-11-14 09:24
On my end, I did test on a MacBook Air (Retina, 13-inch, 2018) under macOS 10.14.6 and on an iMac (Retina 5K, 27-inch, 2019) under macOS 10.15.7.

**Comment by retokromer** [comment] 2020-11-14 09:57
@exekutive I was just trying to file an [issue upstream](https://github.com/Homebrew/homebrew-core/issues/64781), but you were faster!

**Comment by retokromer** [comment] 2020-11-14 14:04
Closing, because this is not related to our formula. In addition, macOS 10.11 is not supported.

**Closed by retokromer** 2020-11-14 14:04 UTC
Labels: macOS 10.11

**Comment by exekutive** [comment] 2020-11-14 21:15
I agree it's probably not formula related.

However I hope you begin to support MacOS 10.11 soon because it is now being pushed out to all compatible machines.

**Comment by exekutive** [comment] 2020-11-14 21:18
> I was just trying to file an issue

Did you submit to x264 developers?

**Comment by inferiorhumanorgans** [comment] 2020-11-20 10:12
> On my end, I did test on a MacBook Air (Retina, 13-inch, 2018) under macOS 10.14.6 and on an iMac (Retina 5K, 27-inch, 2019) under macOS 10.15.7.

I see the same error with macOS 10.14.6 on a Radeon+Iris MacBook Pro and x264 r3027.

**Comment by retokromer** [comment] 2020-11-20 10:25
@exekutive Do you mean macOS 11.0 or 10.11? No, I did not submit an issue to x264, because I cannot reproduce on my end.

**Comment by exekutive** [comment] 2020-11-20 18:38
Sorry, I meant to type OS 11 Big Sur

**Comment by retokromer** [comment] 2020-11-21 12:31
@exekutive On an Intel machine under macOS 11.0.1 the formula works on my end. I cannot test on ARM64, because I don’t have such a machine.

@inferiorhumanorgans Please report upstream.
