### ISSUE TITLE
ERROR: libmp3lame >= 3.98.3 not found

### ISSUE THREAD

**Issue by ZGilbert** [homebrew-ffmpeg/homebrew-ffmpeg#51] opened 2020-09-16 09:05 UTC
hello,  
when I use " brew upgrade homebrew-ffmpeg/ffmpeg/ffmpeg " , I get an error "ERROR: libmp3lame >= 3.98.3 not found"..

**Comment by retokromer** [comment] 2020-09-18 18:48
Do you have more information? Please post the command you tried and the result you got. On which system are you working?

**Comment by retokromer** [comment] 2020-09-21 07:47
@ZGilbert Could you possibly give any additional information? I cannot reproduce.

**Comment by retokromer** [comment] 2020-10-12 11:06
I cannot reproduce and I am closing. Feel free to reopen if there is more information.

**Closed by retokromer** 2020-10-12 11:06 UTC
Labels: need-feedback
