### ISSUE TITLE
make fails compiling

### ISSUE THREAD

**Issue by lucatze** [homebrew-ffmpeg/homebrew-ffmpeg#81] opened 2021-04-28 07:32 UTC
## Bug Reports

⚠️ **This is for bug reports with the `homebrew-ffmpeg` tap only.** Please do not file a bug report if your issue relates to any of the following:

- Homebrew itself (see the [brew](https://github.com/Homebrew/brew/) issue tracker or their [discussion forum](https://github.com/Homebrew/discussions/discussions))
- The `ffmpeg` formula officially supplied by Homebrew
- An error with ffmpeg itself (use [trac.ffmpeg.org](https://trac.ffmpeg.org/) to file a bug, or the [`ffmpeg-user` mailing list](https://ffmpeg.org/contact.html#MailingLists))

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.**

- [x] I ran `brew update` and can still reproduce the problem
- [x] I ran `brew doctor`, fixed all issues and can still reproduce the problem
- [x] I ran `brew config` and `brew doctor` and included their output with my issue
- [x] I verified that this is an issue with *this* tap and not any other `ffmpeg` version

## Expected behavior

Compilation and installation of ffmpeg according to flags.

## Actual behavior

make process aborts with error message

## Command

The exact command you were trying to run:

```
brew install homebrew-ffmpeg/ffmpeg/ffmpeg  -s --with-srt --with-openssl@1.1 --with-openssl --with-openjpeg --with-decklink --with-fdk-aac  --with-libssh --with-game-music-emu
```

The output that you got:

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 108 formulae.
==> Updated Casks
Updated 54 casks.
==> Deleted Casks
clipbuddy                              cliqz                                  cuteclips                              tracks-live

==> Installing ffmpeg from homebrew-ffmpeg/ffmpeg
==> Downloading https://ghcr.io/v2/homebrew/core/srt/manifests/1.4.3
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/srt/blobs/sha256:5f8231fcfa94e640638c5a6b38e75630d48338118a578308dea0fa7e0deaadfd
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:5f8231fcfa94e640638c5a6b38e75630d48338118a578308dea0fa7e0deaadfd?se=2
######################################################################## 100.0%
==> Downloading https://ffmpeg.org/releases/ffmpeg-4.4.tar.xz
Already downloaded: /Users/luke/Library/Caches/Homebrew/downloads/837c094bbbd62f9664825da5b8206acd9a27ed63510f91410034a4a1572d3750--ffmpeg-4.4.tar.xz
==> Installing dependencies for homebrew-ffmpeg/ffmpeg/ffmpeg: srt
==> Installing homebrew-ffmpeg/ffmpeg/ffmpeg dependency: srt
==> Pouring srt--1.4.3.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/srt/1.4.3: 20 files, 4.2MB
==> Installing homebrew-ffmpeg/ffmpeg/ffmpeg --with-decklink --with-fdk-aac --with-game-music-emu --with-libssh --with-openjpeg --with-openssl --wi
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/4.4-with-options --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --e
==> make install
Last 15 lines from /Users/luke/Library/Logs/Homebrew/ffmpeg/02.make:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/atomic:1847:21: error: unknown type name 'ptrdiff_t'
    _Tp* operator-=(ptrdiff_t __op) volatile _NOEXCEPT {return fetch_sub(__op) - __op;}
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/atomic:1849:21: error: unknown type name 'ptrdiff_t'
    _Tp* operator-=(ptrdiff_t __op) _NOEXCEPT          {return fetch_sub(__op) - __op;}
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/atomic:2182:46: error: unknown type name 'ptrdiff_t'
atomic_fetch_add(volatile atomic<_Tp*>* __o, ptrdiff_t __op) _NOEXCEPT
                                             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
3 errors generated.
make: *** [libavdevice/decklink_common.o] Error 1
make: *** Waiting for unfinished jobs....
20 errors generated.
make: *** [libavdevice/decklink_dec.o] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues
```

## Output of `brew config` and `brew doctor` commands

`brew config`:

```
HOMEBREW_VERSION: 3.1.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: d89eda09abbeae907eb88bd6d01dc9cde7ff0e19
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5571ad2bec4ef62ba3b28b51528bcd74899a31d3
Core tap last commit: 17 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit ivybridge
Clang: 12.0 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.5
```

`brew doctor`:

```
Your system is ready to brew.
```

**Comment by slhck** [comment] 2021-04-28 08:07
Seems related to DeckLink, see also https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/64 — I am afraid I cannot help with this, but @retokromer has some experience building with DeckLink support.

**Comment by retokromer** [comment] 2021-04-28 09:20
I am sorry, I do not have access to macOS 11.2.3 at the moment. Possibly during the weekend.

**Comment by Wicky2k8** [comment] 2021-04-28 19:31
Same issue, on Mac 11.3 (note also got it just before I upgraded when I was on 11.2.3)

`HOMEBREW_VERSION: 3.1.4-20-g79fc33c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 79fc33cf39fb516f7ed4416a132db3da34c62a1f
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9a150c193c962a7755b72f30e7d5e4d715b4081f
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.WtlxfydRlH/org.xquartz:0
HOMEBREW_EDITOR: /usr/bin/open -e
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1205
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5`

**Comment by balupton** [comment] 2021-05-18 04:09
Encountered this moving from a 2017 MBP to the M1 Mac Mini

Removing the DeckLink option worked for me.

Here is a bash script to do it:

``` bash
	# install with all the options
	opts="$(brew options homebrew-ffmpeg/ffmpeg/ffmpeg --compact)"
	# https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/81#issuecomment-828722622
	opts="${opts/--with-decklink /}"
	# install
	brew install homebrew-ffmpeg/ffmpeg/ffmpeg $opts
```

**Comment by retokromer** [comment] 2021-05-18 05:31
We have FFmpeg installations using DeckLink in Israel which are scheduled to go in production tomorrow. I will report if there are any issues. In Switzerland our settings are working well since almost half a year. (As explained in our ReadMe document, the DeckLink SDK must be installed before FFmpeg.)

**Comment by Wicky2k8** [comment] 2021-05-28 22:53
Note, this is fixed in the HEAD version

**Comment by retokromer** [comment] 2021-05-29 07:24
Thank you, @Wicky2k8, for your note. On the mailing list I didn’t notice any change on the DeckLink integration, but possibly I missed that post. I will try to delve into this in the next weeks, and to check if a patch is needed for FFmpeg 4.4. I am sorry, I could not reproduce so far.

**Comment by lucatze** [comment] 2021-05-29 15:14
But HEAD Version means that i cant use additional compilation flags, right? Because id also like to have fdk_aac included.

**Comment by retokromer** [comment] 2021-05-29 15:59
FYI: The AMIA formula for the version 12 of the DeckLink SDK should be live soon.

**Comment by retokromer** [comment] 2021-05-29 15:59
>But HEAD Version means that i cant use additional compilation flags, right?

Yep.

**Comment by Wicky2k8** [comment] 2021-05-29 16:26
Thread on this from the AMIA tap, might shed some light for those that understand the patch:
https://github.com/amiaopensource/homebrew-amiaos/issues/284

**Comment by retokromer** [comment] 2021-05-29 17:12
@Wicky2k8 see https://github.com/amiaopensource/decklinksdk/pull/10

**Closed** 2021-06-02 10:26 UTC

**Comment by retokromer** [comment] 2021-06-06 05:35
Regarding DeckLink see also: https://forum.blackmagicdesign.com/viewtopic.php?f=4&t=121992#p699837
